# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: piotr-yuxuan/walter-ci
description: Collection of `bash` utilities and helpers accessible from the comfort of your command line.
inputs:
  github-token:
    description: >+
      To fix rate limit errors, provide `secrets.GITHUB_TOKEN` value to this field.
      More info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@911bc4413d0c9a0d15a435af6a7181353a453e8c
      with:
        cli: latest
        lein: latest
        github-token: ${{ inputs.GITHUB_TOKEN }}
    - run: GIT_ASKPASS='' git clone https://github.com/practicalli/clojure-deps-edn.git $XDG_CONFIG_HOME/clojure
      shell: bash
    - run: mkdir "$HOME/.walter-ci"
      shell: bash
    - run: |
        WALTER_VERSION=$(awk '{$1=$1};1' < "${GITHUB_ACTION_PATH}/resources/walter-ci.version")
        wget --quiet "https://github.com/piotr-yuxuan/walter-ci/releases/download/${WALTER_VERSION}/walter-ci-standalone.jar" -O "$HOME/.walter-ci/walter-ci-standalone.jar"
      shell: bash
    - run: cp "${GITHUB_ACTION_PATH}/bash/walter-ci.sh" "$HOME/.walter-ci/walter"
      shell: bash
    - run: chmod +x "$HOME/.walter-ci/walter"
      shell: bash
    - run: echo "$HOME/.walter-ci" >> $GITHUB_PATH
      shell: bash
    - run: cp "${GITHUB_ACTION_PATH}/resources/profiles.clj" "${LEIN_HOME}/profiles.clj"
      shell: bash
    - run: cp "${GITHUB_ACTION_PATH}/bash/askpass.sh" "$HOME/.walter-ci/askpass.sh"
      shell: bash

author: Piotr Yuxuan
branding:
  icon: command
  color: orange
