name: 'piotr-yuxuan/walter-ci'
description: |
  Opinionated set of standard steps for all your Clojure projects, defined by conventions and no configuration.
outputs:
  see_installation:
    description: 'See installation in the README'
    value: |
      Refer the `main` branch to automatically upgrade this action across
      all your repositories. This makes the most of Walter, otherwise you
      lose the benefits of it.
runs:
  using: "composite"
  steps:
    - run: echo 'See installation in the README'.
      shell: bash
    - run: exit 1
      shell: bash
