# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: piotr-yuxuan/walter-ci
description: Collection of utilities and helpers accessible from the comfort of your command line.
inputs:
  github-token:
    description: >+
      To fix rate limit errors, provide `secrets.GITHUB_TOKEN` value to this field.
      More info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      with:
        submodules: recursive
    - run: |
        cp -r "${GITHUB_ACTION_PATH}/bash" "$HOME/.walter-ci"
        cp -r "${GITHUB_ACTION_PATH}/edn-sources" "$HOME/.walter-ci/edn-sources"

        mv "$HOME/.walter-ci/walter-ci.sh" "$HOME/.walter-ci/walter"
        chmod +x "$HOME/.walter-ci/walter"
        echo "$HOME/.walter-ci" >> $GITHUB_PATH
      shell: bash
    - name: Cache local Maven repository
      uses: actions/cache@8f1e2e02865c42348f9baddbbaafb1841dce610a
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@911bc4413d0c9a0d15a435af6a7181353a453e8c
      with:
        cli: latest
        lein: latest
        bb: latest
        github-token: ${{ inputs.GITHUB_TOKEN }}
    - run: GIT_ASKPASS='' git clone --depth 1 https://github.com/practicalli/clojure-deps-edn.git $XDG_CONFIG_HOME/clojure
      shell: bash
    - run: |
        echo "\$WALTER_VERSION=${WALTER_VERSION} initially"
        WALTER_VERSION_CURRENT=$(awk '{$1=$1};1' < "${GITHUB_ACTION_PATH}/resources/walter-ci.version")
        echo "\$WALTER_VERSION_CURRENT=${WALTER_VERSION_CURRENT}"
        WALTER_VERSION=${WALTER_VERSION:-${WALTER_VERSION_CURRENT}}
        echo "\$WALTER_VERSION=${WALTER_VERSION}"
        wget --quiet "https://github.com/piotr-yuxuan/walter-ci/releases/download/${WALTER_VERSION}/walter-ci-${WALTER_VERSION}-standalone.jar" -O "$HOME/.walter-ci/walter-ci-standalone.jar"
      shell: bash
    - run: cp "${GITHUB_ACTION_PATH}/resources/profiles.clj" "${LEIN_HOME}/profiles.clj"
      shell: bash
    - run: cp "${GITHUB_ACTION_PATH}/resources/settings.xml" "$HOME/.m2/settings.xml"
      shell: bash
    - name: Sanity checks, and first aid debug info
      shell: bash
      run: |
        set +xe
        echo "\$HOME=${HOME}"
        echo "\$${LEIN_HOME}=${LEIN_HOME}"
        tree -Chup "${HOME}/.walter-ci" || true
        tree -Chup "${LEIN_HOME}" || true
        env
        true

author: Piotr Yuxuan
branding:
  icon: command
  color: orange
