# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: piotr-yuxuan/walter-ci
description: Collection of `bash` utilities and helpers accessible from the comfort of your command line.
inputs:
  github-token:
    description: >+
      To fix rate limit errors, provide `secrets.GITHUB_TOKEN` value to this field.
      More info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
  - name: Checkout repository
    uses: actions/checkout@main
    with:
      submodules: recursive
  - name: Cache local Maven repository
    uses: actions/cache@v2
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}-${{ hashFiles('**/deps.edn') }}
      restore-keys: ${{ runner.os }}-maven-
  - name: Install Clojure CLI
    uses: DeLaGuardo/setup-clojure@master
    with:
      cli: latest
      lein: latest
      github-token: ${{ inputs.GITHUB_TOKEN }}
  - name: Install clojure-deps-edn
    shell: bash
    run: GIT_ASKPASS='' git clone https://github.com/practicalli/clojure-deps-edn.git $XDG_CONFIG_HOME/clojure
  - name: Download Walter executable and update PATH
    shell: bash
    run: ${{ github.action_path }}/bash/install.sh
  - name: Copy walter-ci standalone jar and executable shell script
    shell: bash
    run: |-
        mkdir "$HOME/.walter-ci"
        wget --quiet "https://github.com/piotr-yuxuan/walter-ci/releases/latest/download/walter-ci-standalone.jar" -O "$HOME/.walter-ci/walter-ci-standalone.jar"
        cp "${GITHUB_ACTION_PATH}/bash/walter-ci.sh" "$HOME/.walter-ci/walter-ci"
        chmod +x "$HOME/.walter-ci/walter-ci"
        echo "$HOME/.walter-ci" >> $GITHUB_PATH
  - name: Copy profiles.clj
    shell: bash
    run: |-
      cp "${GITHUB_ACTION_PATH}/resources/profiles.clj" "${LEIN_HOME}/profiles.clj"
  - name: Copy askpass.sh
    shell: bash
    run: |-
      cp "${GITHUB_ACTION_PATH}/bash/askpass.sh" "$HOME/.walter-ci/askpass.sh"

author: Piotr Yuxuan
branding:
  icon: command
  color: orange
