name: Walter
on:
  push:
    branches: '*'
env:
  WALTER_GIT_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
jobs:

  #############################################################################
  # Jobs for Walter grooming
  #############################################################################
  code-style:
    runs-on: ubuntu-latest
    name: Fix and report code style
    continue-on-error: true
    steps:
      - uses: actions/checkout@main
      - run: env
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint dev src test
          github_token: ${{ secrets.GITHUB_TOKEN }}
  coverage:
    runs-on: ubuntu-latest
    name: Report code coverage of test
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: lein cloverage
  conform-gh:
    runs-on: ubuntu-latest
    name: Conform GitHub repository
    env:
      WALTER_GITHUB_TOKEN: ${{ secrets.WALTER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - run: env
      - run: sleep 1
  ns-sort:
    runs-on: ubuntu-latest
    name: Sort namespace forms
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: sleep 1
  update:
    runs-on: ubuntu-latest
    name: Update dependency versions
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: sleep 10
  licenses:
    runs-on: ubuntu-latest
    name: List dependency licences
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: sleep 10
  vulnerabilities:
    runs-on: ubuntu-latest
    name: Report known dependency vulnerabilities
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: sleep 300
  documentation:
    runs-on: ubuntu-latest
    name: Update documentation
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - uses: actions/checkout@main
      - run: env
      - run: sleep 30
  funding:
    runs-on: ubuntu-latest
    name: Ensure FUNDING.yml is present
    steps:
      - uses: actions/checkout@main
      - run: sleep 1

  #############################################################################
  # Deploy job, run after grooming jobs if all successful
  #############################################################################
  deploy:
    runs-on: ubuntu-latest
    env:
      WALTER_GITHUB_TOKEN: ${{ secrets.WALTER_GITHUB_TOKEN }}
      WALTER_CLOJARS_TOKEN: ${{ secrets.WALTER_CLOJARS_TOKEN }}
      WALTER_CLOJARS_USERNAME: ${{ secrets.WALTER_CLOJARS_USERNAME }}
    name: Run tests, push git references, and finally deploy artifacts
    needs: [code-style, coverage, conform-gh, ns-sort, update]
    steps:
      - uses: actions/checkout@main
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Run tests
        run: sleep 30
      - name: Push Walter commits and tags to GitHub
        run: sleep 30
      - name: Deploy
        run: sleep 30
