name: Walter
on:
  push:
    branches: '*'
env:
  WALTER_GIT_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
jobs:
  #############################################################################
  # Setup jobs, run in parallel and joined on setup-completed
  #############################################################################
  clojure:
    name: Install Clojure on the worker
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          lein: latest
  walter:
    name: Install Walter on the worker
    steps:
      - run: echo
  checkout:
    name: Checkout project code
    steps:
      - uses: actions/checkout@main
        with:
          - clean: false
  print-env:
    name: Print environment variables
    steps:
      - run: env
  setup-completed:
    name: All setup jobs successful
    needs: [clojure, walter, checkout, print-env]
    steps:
      - name: Success
        run: echo

  #############################################################################
  # Jobs for Walter grooming
  #############################################################################
  code-style:
    name: Fix and report code style
    needs: setup-completed
    continue-on-error: true
    steps:
      - run: echo
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint dev src test
          github_token: ${{ secrets.GITHUB_TOKEN }}
  coverage:
    name: Report code coverage of test
    needs: setup-completed
    steps:
      - run: echo
  conform-gh:
    name: Conform GitHub repository
    needs: setup-completed
    env:
      WALTER_GITHUB_TOKEN: ${{ secrets.WALTER_GITHUB_TOKEN }}
    steps:
      - run: echo
  ns-sort:
    name: Sort namespace forms
    needs: setup-completed
    steps:
      - run: echo
  update:
    name: Update dependency versions
    needs: setup-completed
    steps:
      - if: ${{ github.event_name == 'schedule' }}
        run: echo
  licenses:
    name: List dependency licences
    needs: setup-completed
    steps:
      - if: ${{ github.event_name == 'schedule' }}
        run: echo
  vulnerabilities:
    name: Report known dependency vulnerabilities
    needs: setup-completed
    steps:
      - if: ${{ github.event_name == 'schedule' }}
        run: echo
  documentation:
    name: Update documentation
    needs: setup-completed
    steps:
      - run: echo
  funding:
    name: Ensure FUNDING.yml is present
    needs: setup-completed
    steps:
      - if: ${{ github.event_name == 'schedule' }}
        run: echo
  grooming-completed:
    name: All setup jobs successful
    needs: [code-style, coverage, conform-gh, ns-sort, update, licenses,
            vulnerabilities, documentation, funding, grooming-completed]
    steps:
      - name: Success
        run: echo

  #############################################################################
  # Deploy job, run after grooming jobs if all successful
  #############################################################################
  deploy:
    env:
      WALTER_GITHUB_TOKEN: ${{ secrets.WALTER_GITHUB_TOKEN }}
      WALTER_CLOJARS_TOKEN: ${{ secrets.WALTER_CLOJARS_TOKEN }}
      WALTER_CLOJARS_USERNAME: ${{ secrets.WALTER_CLOJARS_USERNAME }}
    name: Run tests, push git references, and finally deploy artifacts
    needs: grooming-completed
    steps:
      - name: Run tests
        run: echo
      - name: Push Walter commits and tags to GitHub
        run: echo
      - run: echo
