# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: Install Walter workflows
'on':
  repository_dispatch: null
  workflow_dispatch:
    inputs:
      walter-version:
        description: Walter bin version
        required: false
        type: string
  push:
    branches:
    - main
    paths:
    - .github/workflows/deploy.yml
concurrency:
  group: deploy-jobs
  cancel-in-progress: false
env:
  GIT_ASKPASS: ${HOME}/.walter-ci/bin/askpass.sh
  GIT_AUTHOR_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  WALTER_ACTOR: ${{ secrets.WALTER_ACTOR }}
  WALTER_AUTHOR_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  WALTER_GITHUB_PASSWORD: ${{ secrets.WALTER_GITHUB_PASSWORD }}
  WALTER_GIT_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  WALTER_VERSION: ${{ github.event.inputs.walter-version }}
jobs:
  piotr-yuxuan-algo-calisthenics:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/algo-calisthenics \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/algo-calisthenics \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-closeable-map:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/closeable-map \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/closeable-map \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-dove:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/dove \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/dove \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-ephemeral-server:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/ephemeral-server \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/ephemeral-server \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-malli-cli:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/malli-cli \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/malli-cli \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-nabab:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/nabab \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/nabab \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-polygam:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/polygam \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/polygam \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-poor-mans-distributed-cache:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/poor-mans-distributed-cache \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/poor-mans-distributed-cache \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-security-mining:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/security-mining \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/security-mining \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-slava:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/slava \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/slava \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-slava-record:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/slava-record \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/slava-record \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-tsv-processing:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/tsv-processing \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/tsv-processing \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-walter-ci:
    runs-on: ubuntu-latest
    environment:
      name: self
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/walter-ci \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/walter-ci \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-welcome-base-api:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: piotr-yuxuan/walter-ci@main
    - run: |-
        walter forward-secret --github-repository piotr-yuxuan/welcome-base-api \
          --secret-name "WALTER_ACTOR" \
          --secret-name "WALTER_AUTHOR_NAME" \
          --secret-name "WALTER_CLOJARS_PASSWORD" \
          --secret-name "WALTER_CLOJARS_USERNAME" \
          --secret-name "WALTER_GITHUB_PASSWORD" \
          --secret-name "WALTER_GIT_EMAIL"
    - run: |-
        walter install-workflow --github-repository piotr-yuxuan/welcome-base-api \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-ci.edn" --target-yml "walter-ci.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-cd.edn" --target-yml "walter-cd.yml" \
          --source-edn "$HOME/.walter-ci/edn-sources/workflows/walter-perf.edn" --target-yml "walter-perf.yml"
