# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: Deploy Walter
'on':
  workflow_dispatch: null
  repository_dispatch: null
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
concurrency:
  group: deploy-jobs
  cancel-in-progress: false
env:
  GIT_ASKPASS: ${HOME}/.walter-ci/bin/askpass.sh
  GIT_AUTHOR_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  WALTER_ACTOR: ${{ secrets.WALTER_ACTOR }}
  WALTER_AUTHOR_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  WALTER_GITHUB_PASSWORD: ${{ secrets.WALTER_GITHUB_PASSWORD }}
  WALTER_GIT_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
jobs:
  piotr-yuxuan-walter-ci:
    name: piotr-yuxuan/walter-ci
    runs-on: ubuntu-latest
    environment:
      name: self
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/walter-ci"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"

  piotr-yuxuan-algo-calisthenics:
    name: piotr-yuxuan/algo-calisthenics
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/algo-calisthenics"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-closeable-map:
    name: piotr-yuxuan/closeable-map
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/closeable-map"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-dove:
    name: piotr-yuxuan/dove
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "name: piotr-yuxuan/dove"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-ephemeral-server:
    name: piotr-yuxuan/ephemeral-server
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/ephemeral-server"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-malli-cli:
    name: piotr-yuxuan/malli-cli
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/malli-cli"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-nabab:
    name: piotr-yuxuan/nabab
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "name: piotr-yuxuan/nabab"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-polygam:
    name: piotr-yuxuan/polygam
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "name: piotr-yuxuan/polygam"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-poor-mans-distributed-cache:
    name: piotr-yuxuan/poor-mans-distributed-cache
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/poor-mans-distributed-cache"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-security-mining:
    name: piotr-yuxuan/security-mining
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/security-mining"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-slava:
    name: piotr-yuxuan/slava
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "name: piotr-yuxuan/slava"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-slava-record:
    name: piotr-yuxuan/slava-record
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/slava-record"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-tsv-processing:
    name: piotr-yuxuan/tsv-processing
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/tsv-processing"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
  piotr-yuxuan-welcome-base-api:
    name: piotr-yuxuan/welcome-base-api
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      TARGET_REPOSITORY: "piotr-yuxuan/welcome-base-api"
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-ci.edn" --target-yml "walter-ci.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-cd.edn" --target-yml "walter-cd.yml"
      - run: walter install-workflow --source-edn "$HOME/.walter-ci/edn-sources/walter-perf.edn" --target-yml "walter-perf.yml"
