name: Replicate Walter CI
'on':
  push:
    branches: '*'
jobs:
  replicate-walter-ci:
    runs-on: ubuntu-latest
    env:
      WALTER_GITHUB_PASSWORD: ${{ secrets.WALTER_GITHUB_PASSWORD }}
      WALTER_GIT_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
    steps:
      - uses: actions/checkout@main
      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          lein: latest

      - name: Run tests
        uses: piotr-yuxuan/walter-ci@main
        env:
          WALTER_COMMAND: run-tests

      - name: Walter CI
        uses: piotr-yuxuan/walter-ci@main
        env:
          WALTER_COMMAND: replicate-walter-ci
