name: Walter CI
on:
  push:
    branches: '*'
  schedule:
    - cron: "0 0 1 * *"
jobs:
  walter-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: env
      - env:
          DEBUG: true
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}"
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}"
        run: lein deploy clojars
