name: Walter CI
on:
  push:
    branches: '*'
  schedule:
    - cron: "0 0 1 * *"
jobs:
  walter-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
#      - env:
#          WALTER_CLOJARS_USERNAME: ${{ secrets.WALTER_CLOJARS_USERNAME }}"
#          WALTER_CLOJARS_PASSWORD: ${{ secrets.WALTER_CLOJARS_PASSWORD }}"
#        uses: docker://piotryuxuan/walter-ci:latest
      # It looks difficult set up Docker in the unprivileged Docker
      # provided by Github Actions. As a shortcut, in order to push
      # Walter CI's image, let's use off-the-shelf actions.
      - uses: docker/setup-qemu-action@v1.0.2
      - uses: docker/setup-buildx-action@v1.1.2
      - uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          tags: piotryuxuan/walter-ci:latest
