name: Walter CI
on:
  push:
    branches: '*'
  schedule:
    - cron: "0 0 1 * *"
jobs:
  walter-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: env
      - run: pwd
      - run: id
      - run: ls -hal
      - run: sh ./resources/walter-ci.sh
