name: Walter CI
on:
  push:
    branches: '*'
  schedule:
    - cron: "0 0 1 * *"
jobs:
  walter-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: latest
          lein: latest
      - run: env
      - run: lein deploy clojars
        env:
          DEBUG: true
      - run: clojure -Sdeps '{:aliases {:walter-ci {:replace-deps {com.github.piotr-yuxuan/walter-ci {:mvn/version "LATEST"}}}}}' -M:walter-ci -m com.piotr-yuxuan.walter-ci.main
        env:
          WALTER_CLOJARS_USERNAME: ${{ secrets.WALTER_CLOJARS_USERNAME }}"
          WALTER_CLOJARS_PASSWORD: ${{ secrets.WALTER_CLOJARS_PASSWORD }}"
