# This file is maintained by Walter CI, and may be rewritten.
# https://github.com/piotr-yuxuan/walter-ci
#
# You are free to remove this project from Walter CI realm by opening
# a PR. You may also create another workflow besides this one.

name: Walter CD
'on':
  workflow_dispatch: null
  repository_dispatch: null
  push:
    branches: '*'
concurrency:
  group: walter-cd
  cancel-in-progress: true
env:
  GIT_COMMITTER_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.WALTER_AUTHOR_NAME }}
  GIT_AUTHOR_EMAIL: ${{ secrets.WALTER_GIT_EMAIL }}
  GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GIT_ASKPASS: ${HOME}/.walter-ci/bin/askpass.sh
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: lein with-profile +walter/kaocha,+kaocha run -m kaocha.runner --skip-meta :slow --skip-meta :perf
  report-vulnerabilities:
    name: Scan and report vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: git rm "./doc/Known vulnerabilities.txt" || true
      - run: clojure -T:security/nvd nvd.task/check :classpath '"'"$(lein with-profile -user,-dev classpath)"'"' || true
      - run: cp ./target/nvd/dependency-check-report.csv ./doc/known-vulnerabilities.csv
      - run: $(git diff --exit-code); VARIABLE=$?
      - run: [[ ${VARIABLE} -eq 1 ]] && git add ./doc/known-vulnerabilities.csv
      - run: [[ ${VARIABLE} -eq 1 ]] && git commit --message "Update known vulnerabilities"
      - run: [[ ${VARIABLE} -eq 1 ]] && walter retry -- git push
  list-licences:
    name: List dependency licences
    runs-on: ubuntu-latest
    steps:
      - uses: piotr-yuxuan/walter-ci@main
      - run: lein licenses :csv > ./doc/Licenses.csv
      - run: sort -o ./doc/Licenses.csv{,}
      - run: $(git diff --exit-code); VARIABLE=$?
      - run: [[ ${VARIABLE} -eq 1 ]] && git add ./doc/Licenses.csv
      - run: [[ ${VARIABLE} -eq 1 ]] && git commit --message "List dependency licenses" || true
      - run: [[ ${VARIABLE} -eq 1 ]] && walter retry -- git push || true
  package-deploy-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo :package-deploy-artifacts
